version: '3.8'  # Specify Docker Compose file version

services:
  mysql:
    image: mysql:8.0  # Use official MySQL 8.0 image
    container_name: mysql-container  # Optional name for the container
    environment:
      MYSQL_ROOT_PASSWORD: sagar  # Set root password
      MYSQL_DATABASE: testdb  # Create a database
      MYSQL_USER: sagar  # Create a user
      MYSQL_PASSWORD: sagar123  # Set user password
    ports:
      - 3306:3306  # Map host port 3306 to container port 3306
    volumes:
      - mysql-data:/var/lib/mysql  # Create a volume for persistent data

volumes:
  mysql-data:  # Define the named volume for data persistence