spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: sagar
    url: jdbc:mysql://localhost:3306/testqa
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


