spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: sagar123
    url: jdbc:mysql://localhost:3306/testdb
    username: sagar
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
